# Generated by Django 5.1.4 on 2025-04-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone_number", "0001_initial"),
        ("transaction", "0002_creditrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="phone_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="phone_number.phonenumber",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                    ("charge", "Charge"),
                ],
                max_length=10,
            ),
        ),
    ]
