# Generated by Django 5.1.4 on 2025-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
